version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    # Add database dependency if needed
    # depends_on:
    #   - db

  # Uncomment if you need a database
  # db:
  #   image: postgres:14
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_USER=${DB_USER:-postgres}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME:-myapp}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# Uncomment if using volumes
# volumes:
#   postgres_data:
